name: Continuous integration

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

on:
    push:
      branches:
        - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Set up node
              uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'yarn'
            - name: Install
              run: yarn install --frozen-lockfile
            - name: Lint
              run: npm run lint
            - name: Build
              run: npm run build
